Tradotto l'articolo "Web Components"
reactjs/it.reactjs.org pull request #207
Opened 2020-01-22 01:52 UTC by EmiSan1998

Ho tradotto in Italiano il mio primo articolo della documentazione di React, in futuro traducerò ulteriori articoli della sezione analoga.

2020-05-14 13:46 UTC, paggiorowarda commented on content/docs/web-components.md
> +> Questo codice **NON** funzionerà se le classi saranno convertite con con Babel. Vedi [questa issue](https://github.com/w3c/webcomponents/issues/587) per la discussione.
Occhio al doppio "con" nella frase "classi saranno convertite con con"

2020-11-02 00:23 UTC, DennisBoanini commented on content/docs/web-components.md
> +> I Web Components spesso espongono una API imperativa. Per esempio, un Web Component `video` potrebbe esporre le funzioni `play()` e `pausa()`. Per accedere all'API imperativa di un Web Component av
Dato che `play` non lo hai tradotto forse non tradurrei nemmeno `pause`, che ne pensi?

2020-11-02 00:30 UTC, DennisBoanini requested changes

2020-11-02 00:30 UTC, DennisBoanini commented on content/docs/web-components.md
> +> I Web Components spesso espongono una API imperativa. Per esempio, un Web Component `video` potrebbe esporre le funzioni `play()` e `pausa()`. Per accedere all'API imperativa di un Web Component av
Dato che `play` non lo hai tradotto forse non tradurrei nemmeno `pause`, che ne pensi?

Occhio al secondo periodo, il testo originale usa il plurale `To access the imperative APIs of a..` mentre tu lo hai trasformato in singolare. Propongo, come traduzione `Per accedere alle API imperative di un ...`

La frase `that behaves as a wrapper` la tradurrei come `che si comportano come`

2020-11-02 00:30 UTC, DennisBoanini commented on content/docs/web-components.md
> +Una fonte comune di confusione è che gli Web Components usano l'attributo "class" invece di "className".
```suggestion
Una fonte comune di confusione è che i Web Components usano l'attributo "class" invece di "className".
```

2023-04-20 19:00 UTC, closed without merging