Feature/58 accessibility
reactjs/it.reactjs.org pull request #253
Opened 2020-11-13 16:56 UTC by DennisBoanini

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +- [W3C mostra come etichettare gli elementi](https://www.w3.org/WAI/tutorials/forms/labels/)
```suggestion
- [W3C mostra come etichettare elementi](https://www.w3.org/WAI/tutorials/forms/labels/)
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Sebbene tutte queste pratiche standard HTML possano essere usate in React, nota che l'attributo `for` in JSX viene scritto come `htmlFor`:
```suggestion
Sebbene tutte queste pratiche standard possano essere utilizzate in React, tieni presente che l'attributo `for` in JSX viene scritto come `htmlFor`:
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Gli errori devono essere compresi da tutti gli utenti. I link seguenti mostrano come esporre testi di errore ai lettori di schermo:
```suggestion
Gli errori devono essere compresi da tutti gli utenti. Le seguenti risorse mostrano come esporre testi di errore ai lettori di schermo:
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Assicurati che la tua applicazione web sia totalmente compatibile con le operazioni fatte da tastiera:
```suggestion
Assicurati che la tua applicazione web sia totalmente utilizzabile tramite tastiera:
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Il focus della tastiera fa riferimento all'elemento del DOM selezionato per accettare un input da tastiera. É semplicemente riconoscibile come un contorno sul campo di input come quello che si vede n
```suggestion
Il focus della tastiera fa riferimento all'elemento del DOM selezionato per accettare un input. É semplicemente riconoscibile come un contorno sul campo di input come quello che si vede nell'immagine seguente:
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ### Mechanisms to skip to desired content {#mechanisms-to-skip-to-desired-content}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  Skiplinks or Skip Navigation Links are hidden navigation links that only become visible when keyboard users interact with the page. They are very easy to implement with internal page anchors and some
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Utilizza elementi di riferimento e ruoli, come ad esempio `<main>` and `<aside>`, per creare delle regioni nella pagina per permettere all'utente di navigare da una sezione all'altra.
```suggestion
Utilizza elementi di riferimento e ruoli, come ad esempio `<main>` e `<aside>`, per creare delle regioni, all'interno della pagina, per permettere all'utente di navigare da una sezione all'altra.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ### Programmatically managing focus {#programmatically-managing-focus}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Un'applicazione React modifica continuamente il DOM dell'applicazione durante la sua esecuzione, quindi qualche volte è possibile che il focus della tastiera venga perso oppure sia su un elemento div
```suggestion
Un'applicazione React modifica continuamente il DOM durante la sua esecuzione, quindi qualche volte è possibile che il focus della tastiera venga perso oppure si trovi su un elemento diverso da quello che ci si aspettava. Per correggere questo comportamento errato è necessario intervenire programmaticamente, ad esempio resettando il focus della tastiera sul bottone che ha aperto una finestra modale dopo che è stata chiusa.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Qualche volta un componente padre necessita di fare focus su un elemento in un componente figlio. E' possibile raggiungere questo scopo [esponendo il refs del DOM al componente padre](/docs/refs-and-
```suggestion
Qualche volta un componente padre necessita di fare focus su un elemento di un componente figlio. E' possibile raggiungere questo scopo [esponendo il refs del DOM al componente padre](/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components) attraverso delle speciali prop, nel componente figlio, che inoltra il ref ai nodi figli.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Qualche volta un componente padre necessita di fare focus su un elemento in un componente figlio. E' possibile raggiungere questo scopo [esponendo il refs del DOM al componente padre](/docs/refs-and-
Chiedo consiglio per tradurre meglio l'ultimo pezzo di frase

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ## Mouse and pointer events {#mouse-and-pointer-events}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +>Sebbene questa sia una caratteristica di accessibilità molto importante, è anche una tecnica che dovrebbe essere usata con giudizio. Usalo per aggiustare il focus della tastiera quando è disturbato,
```suggestion
>Sebbene questa sia una caratteristica di accessibilità molto importante, è anche una tecnica che dovrebbe essere usata con giudizio. Usalo per aggiustare il focus della tastiera quando è rotto piutoosto che cercare di anticipare le mosse dell'utente 
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +>anticipare le mosse dell'utente.
```suggestion
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Assicurati che tutte le funzionalità accessibili da mouse siano anche accessibili utilizzando solamente la tastiera. Dipendere solamente da elementi di puntamento portano gli utenti che utilizzano so
```suggestion
Assicurati che tutte le funzionalità accessibili da mouse siano anche accessibili utilizzando solamente la tastiera. Dipendere solamente da elementi di puntamento porta gli utenti che utilizzano solo la tastiera a non utilizzare la tua applicazione.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Questo può funzionare bene per gli utenti che usano strumenti di puntamento, come ad esempio un mouse, ma utilizzando solamente la tastiera porta ad una rottura della funzionalità quando ci spostiamo
```suggestion
Questo può funzionare bene per gli utenti che usano strumenti di puntamento, come ad esempio un mouse, ma utilizzando solamente la tastiera porta ad una rottura della funzionalità quando ci spostiamo sul successivo elemento col pulsante di Tab, in quanto l'oggetto `window` non riceverà mai l'evento di `click`. Questo errato comportamento può portare a nascondere una certa funzionalità dell'applicazione e di conseguenza ad un allontamento degli utenti.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +La stessa funzionalità può essere ottenuta semplicemente utilizzando in modo appropriato eventi come `onBlur` e `onFocus`:
```suggestion
La stessa funzionalità può essere ottenuta semplicemente utilizzando in modo appropriato eventi come `onBlur` e `onFocus`:
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Il codice appena visto mostra come esporre la funzionalità sia per utenti che usano strumenti di puntamento sia per utenti che usano la tastiera. Nota anche che è stata aggiunta la props `aria-*` per
```suggestion
Il codice appena visto mostra come esporre la funzionalità sia per utenti che usano strumenti di puntamento sia per utenti che usano la tastiera. Nota anche che è stata aggiunta la props `aria-*` per fornire supporto agli utenti che utilizzano i lettori di schermo. Per semplicità l'evento della tastiera per abilitare l'interazione con il popover tramite `tasti freccia` non è stato implementato.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Questo è solo un esempio di molti dove dipendere solamente da dispositivi di puntamento e eventi del mouse portano ad una rottura delle funzionalità delle tastiera degli utenti. Testare sempre con la
```suggestion
Questo è solo un esempio di molti casi dove dipendere solamente da dispositivi di puntamento e eventi del mouse portano ad una rottura delle funzionalità per gli utenti che utilizzano la tastiera. Testare sempre con la tastiera evidenzia immediatamente eventuali problemi che dovranno essere corretti utilizzando eventi della tastiera.
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ## More Complex Widgets {#more-complex-widgets}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ## Other Points for Consideration {#other-points-for-consideration}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Scrivete in un linguaggio naturale i testi delle pagine in modo tale che i lettori di schermo possono effettuare le corrette impostazioni della voce:
Chiedo aiuta per una migliore traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  - [WCAG - Understanding the Document Title Requirement](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html)
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ### Color contrast {#color-contrast}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  - [WCAG - Understanding the Color Contrast Requirement](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  - [Everything About Color Contrast And Why You Should Rethink It](https://www.smashingmagazine.com/2014/10/color-contrast-tips-and-tools-for-accessibility/)
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  - [A11yProject - What is Color Contrast](https://a11yproject.com/posts/what-is-color-contrast/)
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
> +Se vuoi estenedere per conto tuo il test sul contrasto dei colori puoi utilizzare i seguenti strumenti:
```suggestion
Se vuoi estendere per conto tuo il test sul contrasto dei colori puoi utilizzare i seguenti strumenti:
```

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ### The keyboard {#the-keyboard}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ### Development assistance {#development-assistance}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  ### Testing accessibility in the browser {#testing-accessibility-in-the-browser}
Manca traduzione

2020-11-13 17:44 UTC, DennisBoanini commented on content/docs/accessibility.md
>  #### Accessibility inspectors and the Accessibility Tree {#accessibility-inspectors-and-the-accessibility-tree}
Manca traduzione

2020-11-19 17:05 UTC, DennisBoanini commented
@deblasis

2020-11-20 09:38 UTC, deblasis requested changes
Ottimo lavoro! 👍

2020-11-20 09:38 UTC, deblasis commented on content/docs/accessibility.md
> +In questi casi possiamo usare i [Fragments di React](/docs/fragments.html) per raggruppare più elmenti insieme.
```suggestion
In questi casi possiamo usare i [Fragments di React](/docs/fragments.html) per raggruppare più elementi insieme.
```

2020-11-20 09:38 UTC, deblasis commented on content/docs/accessibility.md
> +Ogni elemento di un form, come ad esempio `<input>` e `<textarea>`, necessitano di essere etichettati come accessibili. É necessario mettere label descrittive, dato che queste vengono processate dai
Il soggetto, elemento, e' singolare
```suggestion
Ogni elemento di un form, come ad esempio `<input>` e `<textarea>`, necessita di essere etichettato come accessibile. É necessario mettere label descrittive, dato che queste vengono processate dai lettori di schermi.
```

2020-11-20 09:38 UTC, deblasis commented on content/docs/accessibility.md
> +>Sebbene questa sia una caratteristica di accessibilità molto importante, è anche una tecnica che dovrebbe essere usata con giudizio. Usalo per aggiustare il focus della tastiera quando è rotto piutt
Il soggetto, tecnica, e' femminile
```suggestion
>Sebbene questa sia una caratteristica di accessibilità molto importante, è anche una tecnica che dovrebbe essere usata con giudizio. Usala per aggiustare il focus della tastiera quando è rotto piuttosto che cercare di anticipare le mosse dell'utente 
```

2020-11-20 09:38 UTC, deblasis commented on content/docs/accessibility.md
> +Deque Systems offre [aXe-core](https://github.com/dequelabs/axe-core) per test end-to-end e automatici di accessibilità. Questo modulo include alcune integrazioni per Selenium.
Meglio?
```suggestion
Deque Systems offre [aXe-core](https://github.com/dequelabs/axe-core) per test di accessibilità end-to-end automatizzati. Questo modulo include alcune integrazioni per Selenium.
```

2020-11-20 18:19 UTC, DennisBoanini commented
> 
> 
> Ottimo lavoro! 👍

Grazie mille 😍

2020-11-22 15:21 UTC, deblasis approved these changes

2020-11-22 15:21 UTC, merged