Translate Reconciliation
reactjs/it.reactjs.org pull request #262
Opened 2021-01-07 17:10 UTC by mattveraldi

Ciao, I finished the issue #71 .
On the _"Chiavi"_ paragraph, I chose to keep using `key` instead of translating it as 'chiave' because, in my opinion, it is more clear for the user that _we are specifically referring to the prop itself_, not only the concept. Let me know if it is ok for you to keep using 'key'. If that is the case, maybe we could consider to add it in the [Glossary](https://github.com/reactjs/it.reactjs.org/blob/master/GLOSSARY.md). Let me know if I should fix something on the translation or on the sentences and I will do it asap 😄 👍

2021-01-17 16:26 UTC, mattveraldi commented
Any news so far?

2021-01-18 12:02 UTC, deblasis commented
> Any news so far?

Ciao @mattveraldi!
I agree with keeping `key` untranslated because it's a **key concept**, pun intended 😄 

There's a merge conflict, as soon as you fix it I'll review so that we can merge.

2021-01-18 15:38 UTC, deblasis requested changes
Great job!

2021-01-18 15:38 UTC, deblasis commented on content/docs/reconciliation.md
> +2. Le chiavi dovrebbero essere stabili, predicibili ed univoche. Chiavi non stabili (come quell prodotte da `Math.random()`) causeranno la ricreazione unutile di diverse istanze dei componenti e nodi
```suggestion
2. Le chiavi dovrebbero essere stabili, predicibili ed univoche. Chiavi non stabili (come quell prodotte da `Math.random()`) causeranno l'inutile ricreazione di diverse istanze dei componenti e nodi DOM, ciò può causare degradazione delle prestazioni e perdita di state nei componenti figlio.
```

2021-01-18 17:07 UTC, mattveraldi commented
> Great job!

Thank you 😄

2021-01-18 17:27 UTC, deblasis approved these changes

2021-01-18 17:27 UTC, merged