Error boundaries translation
reactjs/it.reactjs.org pull request #279
Opened 2021-04-23 22:16 UTC by DennisBoanini

2021-04-23 22:43 UTC, DennisBoanini commented on content/docs/error-boundaries.md
>  > Error boundaries do **not** catch errors for:
Questa riga è da rimuovere
```suggestion
```

2021-04-23 22:43 UTC, DennisBoanini commented on content/docs/error-boundaries.md
> +La granularità dei contenitori di errori dipende interamente da te sviluppatore. Potresti voler wrappare i componenti di rotte di primo livello facendo vedere un messaggio, all'utente, tipo "Qualcosa
```suggestion
La granularità dei contenitori di errori dipende interamente da te sviluppatore. Potresti voler wrappare i componenti di rotte di primo livello facendo vedere un messaggio, all'utente, tipo "Qualcosa è andato storto" proprio come i framework lato server, spesso, gestiscono i crash. Potresti anche voler wrappare singoli widget all'interno di un contenitore di errori per proteggerli da crash che possono avvenire all'interno dell'applicazione.
```

2021-04-23 22:43 UTC, DennisBoanini commented on content/docs/error-boundaries.md
> +Ad esempio Facebook Messenger wrappa il contenuto della barra laterale, del pannello informativo, delle conversazioni e dei messaggi di input in contenitori di errori separati. Se qualche componente
```suggestion
Ad esempio Facebook Messenger wrappa il contenuto della barra laterale, del pannello informativo, delle conversazioni e dei messaggi di input in contenitori di errori separati. Se qualche componente in una delle precedenti aree si rompe, il resto dell'applicazione rimane comunque interattiva.
```

2021-04-23 22:43 UTC, DennisBoanini commented on content/docs/error-boundaries.md
> +Vi incoraggiamo inoltre ad utilizzare dei servizi JavaScript di reportistica (o costruitene una personalizzato) cosicché da capire che tipo di eccezioni vengono sollevate in produzione, e che non ven
```suggestion
Vi incoraggiamo inoltre ad utilizzare dei servizi JavaScript di reportistica (o costruitene una personalizzata) cosicché da capire che tipo di eccezioni vengono sollevate in produzione, e che non vengono catturate, e fixarle.
```

2021-04-23 22:43 UTC, DennisBoanini commented on content/docs/error-boundaries.md
> +Se avete creato l'applicazione senza usare Create React App, potete usare [questo plugin] da aggiungere, manualmente, alla configurazione Babel. Tieni presente che tutto ciò vale solo per l'ambiente
```suggestion
Se avete creato l'applicazione senza usare Create React App, potete usare [questo plugin](https://www.npmjs.com/package/@babel/plugin-transform-react-jsx-source) da aggiungere, manualmente, alla configurazione Babel. Tieni presente che tutto ciò vale solo per l'ambiente di sviluppo e **deve essere disabilitato in produzione**.
```

2021-04-23 22:43 UTC, DennisBoanini commented on content/docs/error-boundaries.md
> +React non ha necessità di contenutori di errori per il gestore degli eventi. A differenza dei metodi di render e dei metodi del ciclo di vita, i gestori degli eventi non si hanno durante il rendering
```suggestion
React non ha necessità di contenitori di errori per il gestore degli eventi. A differenza dei metodi di render e dei metodi del ciclo di vita, i gestori degli eventi non si hanno durante il rendering. Quindi se questi lanciano un errore, React continua comunque a sapere cosa visualizzare sullo schermo.
```

2021-04-23 22:45 UTC, DennisBoanini commented
Chiedo scusa per il ritardo della PR 😞 

@deblasis

2021-04-26 12:46 UTC, deblasis requested changes
Qualche suggerimento, dai uno 👀 please

2021-04-26 12:46 UTC, deblasis commented on content/docs/error-boundaries.md
> +La granularità dei contenitori di errori dipende interamente da te sviluppatore. Potresti voler wrappare i componenti di rotte di primo livello facendo vedere un messaggio, all'utente, tipo "Qualcosa
```suggestion
La granularità dei contenitori di errori è a discrezione dello sviluppatore. Potresti voler wrappare i componenti di rotte di primo livello facendo vedere un messaggio tipo "Qualcosa è andato storto" all'utente proprio come i framework lato server, spesso, gestiscono i crash. Potresti anche voler wrappare singoli widget all'interno di un contenitore di errori per proteggerli da crash che possono avvenire all'interno dell'applicazione.
```

2021-04-26 12:46 UTC, deblasis commented on content/docs/error-boundaries.md
> +E' anche possibile vedere i nomi dei fili e i numeri di linea nello stack trace del componente. Questo è il comportamento di default nei progetti creati con [Create React App](https://github.com/face
```suggestion
E' anche possibile vedere i nomi dei file e i numeri di linea nello stack trace del componente. Questo è il comportamento di default nei progetti creati con [Create React App](https://github.com/facebookincubator/create-react-app):
```

2021-04-26 12:46 UTC, deblasis commented on content/docs/error-boundaries.md
> +Tuttavia i compoenti di React sono molto dichiarativi e specificano cosa deve essere renderizzato:
```suggestion
Tuttavia i componenti di React sono molto dichiarativi e specificano cosa deve essere renderizzato:
```

2021-04-26 12:46 UTC, deblasis commented on content/docs/error-boundaries.md
> +I contenitori di errore preservano la natura dichiarativa di React e si comporta esattamente come ci si aspetta. Ad esempio, anche se l'errore capita nel metodo `componentDidUpdate`, causato da `setS
```suggestion
I contenitori di errore preservano la natura dichiarativa di React e si comportano esattamente come ci si aspetta. Ad esempio, anche se l'errore capita nel metodo `componentDidUpdate`, causato da `setState` sollevato da qualche parte in profondità nell'albero, continuerà a propagare correttamente l'errore al più vicino contenitore di errori.
```

2021-04-26 12:46 UTC, deblasis commented on content/docs/error-boundaries.md
> +React non ha necessità di contenitori di errori per il gestore degli eventi. A differenza dei metodi di render e dei metodi del ciclo di vita, i gestori degli eventi non si hanno durante il rendering
```suggestion
React non ha necessità di contenitori di errori per i gestori degli eventi. A differenza dei metodi di render e dei metodi del ciclo di vita, i gestori degli eventi non si hanno durante il rendering. Quindi se questi lanciano un errore, React continua comunque a sapere cosa visualizzare sullo schermo.
```

2021-04-26 12:46 UTC, deblasis commented
> Chiedo scusa per il ritardo della PR 😞
> 
> @deblasis

Haha! Ma che scherzi!? Figurati

2021-04-26 15:13 UTC, deblasis approved these changes

2021-04-26 15:14 UTC, deblasis commented
Closes #61

2021-04-26 15:14 UTC, merged