Translation in a IDEOMATICALY way, for the page FAQ APIs and AJAX #79
reactjs/it.reactjs.org pull request #299
Opened 2021-07-05 08:47 UTC by adifsgaid

2021-07-09 10:09 UTC, deblasis requested changes
👋 Gli ID delle intestazioni non vanno tradotti, puoi ripristinarli per favore?

2021-07-09 11:31 UTC, adifsgaid commented
Certo 😊 !


Le ven. 9 juil. 2021 à 12:09, Alessandro De Blasis ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
>
> 👋 Gli ID delle intestazioni non vanno tradotti, puoi ripristinarli per
> favore?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/reactjs/it.reactjs.org/pull/299#pullrequestreview-702896758>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPBJL4CKQQLVCPRQHZEIF3TW3DF3ANCNFSM472IXXPA>
> .
>

2021-07-14 07:50 UTC, deblasis requested changes
Ciao! Non mi riferivo ai commenti, quelli va benissimo se vengono tradotti.

Mi riferivo agli ID delle intestazioni come spiegato nella guida di stile:
https://github.com/reactjs/it.reactjs.org/edit/master/STYLE_GUIDE.md

![image](https://user-images.githubusercontent.com/29378614/125584058-1adf9f59-4211-4fbe-8fda-1edea3afd729.png)

2021-07-19 07:53 UTC, deblasis requested changes

2021-07-19 07:53 UTC, deblasis commented on content/docs/faq-ajax.md
> +Puoi usare qualsiasi libreria AJAX con React. Le piu popolari sono [Axios](https://github.com/axios/axios), [jQuery AJAX](https://api.jquery.com/jQuery.ajax/), e il e il browser integrato [window.fet
```suggestion
Puoi usare qualsiasi libreria AJAX con React. Le più popolari sono [Axios](https://github.com/axios/axios), [jQuery AJAX](https://api.jquery.com/jQuery.ajax/), e l'API [window.fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) che è integrata nel browser.
```

2021-07-19 10:22 UTC, deblasis approved these changes
👍

2021-07-19 10:22 UTC, merged