Forwarding refs translation
reactjs/it.reactjs.org pull request #319
Opened 2021-10-03 00:56 UTC by DennisBoanini

2021-10-03 01:11 UTC, DennisBoanini commented
@deblasis

2021-10-04 08:33 UTC, deblasis requested changes
👍

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +L'inoltro delle ref è una tecnica per passare automaticamente una [ref](/docs/refs-and-the-dom.html) attraverso un componente ad uno dei suoi figli. Tipicamente questo non è necessario per la maggior
```suggestion
L'inoltro delle ref è una tecnica per passare automaticamente una [ref](/docs/refs-and-the-dom.html) attraverso un componente ad uno dei suoi figli. Tipicamente questo non è necessario per la maggior parte dei componenti dell'applicazione. Può comunque essere molto utile per alcuni tipi di componenti, specialmente per i componenti riusabili appartenenti alle librerie. Lo scenario più comune è descritto di seguito.
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +I componenti React nascondono i dettagli della loro implementazione, incluso il loro output renderizzato. Altri componenti che usano `FancyButton` **solitamente non hanno bisogno di** [ottenere una r
```suggestion
I componenti React nascondono i dettagli della loro implementazione, incluso il loro output renderizzato. Altri componenti che usano `FancyButton` **solitamente non hanno bisogno di** [ottenere una ref](/docs/refs-and-the-dom.html) dell'elemento interno del DOM `button`. Ciò è ottimo perché previene ai componenti di affidarsi troppo alla struttura DOM l'uno dell'altro.
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +**L'inoltro delle refs è una feature build-in che permette ad alcuni componenti di prendere le `ref` che ricevono e passarle in basso (in altre parole avanti) ai suoi figli.**
```suggestion
**L'inoltro delle refs è una feature opt-in che permette ad alcuni componenti di prendere le `ref` che ricevono e passarle in basso (in altre parole avanti) ai suoi figli.**
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +In questo modo i componenti che usano `FancyButton` può ottenere una ref al nodo del DOM `button` e accedervi, se necessario, proprio come se utilizzassero l'elemento del DOM `button` direttamente.
```suggestion
In questo modo i componenti che usano `FancyButton` possono ottenere una ref al nodo del DOM `button` e accedervi, se necessario, proprio come se utilizzassero l'elemento del DOM `button` direttamente.
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +Qua puoi trovare una spiegazione passo passo di quello che succede nel precedente esempio>
```suggestion
Qui puoi trovare una spiegazione passo passo di quello che succede nel precedente esempio:
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +2. Passiamo la nostra `ref` a `<FancyButton ref={ref}>` specificandolo come un attributo JSX.
```suggestion
2. Passiamo la nostra `ref` a `<FancyButton ref={ref}>` specificandola come un attributo JSX.
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +Questa tecnica può anche essere particolarmente utile con [componenti di tipo higher-order](/docs/higher-order-components.html) (conosciuti anche come HOC). Iniziano con un esempio di che logga le pr
```suggestion
Questa tecnica può anche essere particolarmente utile con [componenti di tipo higher-order](/docs/higher-order-components.html) (conosciuti anche come HOC). Iniziamo con un esempio che logga le props di un componente in console:
```

2021-10-04 08:33 UTC, deblasis commented on content/docs/forwarding-refs.md
> +Fortunatamente possiamo passare le refs esplicitamente al compnente interno `FancyButton` utilizzando le API `React.forwardRef`. `React.forwardRef` accetta una funzione di renderizzazione che riceve
```suggestion
Fortunatamente possiamo passare le refs esplicitamente al componente interno `FancyButton` utilizzando le API `React.forwardRef`. `React.forwardRef` accetta una funzione di renderizzazione che riceve le `props` e le `ref` come parametri e le ritorna ad un nodo React. Ad esempio:
```

2021-10-04 10:08 UTC, DennisBoanini commented
Perdonami per gli errori di distrazione 😞

2021-10-04 13:32 UTC, deblasis approved these changes

2021-10-04 13:33 UTC, deblasis commented
> Perdonami per gli errori di distrazione 😞

Nessun problema, figurati! 😊

2021-10-04 13:33 UTC, merged