Beta website part I
reactjs/it.reactjs.org pull request #374
Opened 2022-07-21 16:11 UTC by deblasis

This PR adds translations for the following pages: 

-  Installation (note: a lot of content here is similar to old website)
    - Start a New React Project

in new BETA website

2022-07-21 16:29 UTC, mattia-sanfilippo requested changes
Ciao Alessandro, mi sono permesso di correggere un po' di typo 😃

2022-07-21 16:29 UTC, mattia-sanfilippo commented on beta/src/pages/learn/installation.md
> +React è stato progettato sin dal principio per essere adottato gradualmente. A seconda dei tuoi gusti, puoi usare il minimo o il maggior numero di funzionalità offerte da React. Se vuoi avere un assa
```suggestion
React è stato progettato sin dal principio per essere adottato gradualmente. A seconda dei tuoi gusti, puoi usare il minimo o il maggior numero di funzionalità offerte da React. Se vuoi avere un assaggio di React, aggiungere un po' di interattività ad una pagina HTML, o sviluppare una applicazione complessa basata su React, questa sezione ti aiuterà nei primi passi.
```

2022-07-21 16:29 UTC, mattia-sanfilippo commented on beta/src/pages/learn/installation.md
> +La maggioranza delle pagine della documentazione di React contengono sandboxes come questa. Al di fuori della documentazione, esistono alcune sandboxes online che supportano Reactç ad esempio, [CodeS
```suggestion
La maggioranza delle pagine della documentazione di React contengono sandboxes come questa. Al di fuori della documentazione, esistono alcune sandboxes online che supportano React: ad esempio, [CodeSandbox](https://codesandbox.io/s/new), [StackBlitz](https://stackblitz.com/fork/react), o [CodePen](https://codepen.io/pen?&editors=0010&layout=left&prefill_data_id=3f4569d1-1b11-4bce-bd46-89090eed5ddb).
```

2022-07-21 16:29 UTC, mattia-sanfilippo commented on beta/src/pages/learn/start-a-new-react-project.md
> +Se intendi **iniziare un progetto pronto al rilascio in produzione,** [Next.js](https://nextjs.org/) è un ottimo punto di partenza. Next.js è un popolare framework leggero per la generazione di conte
```suggestion
Se intendi **iniziare un progetto pronto al rilascio in produzione,** [Next.js](https://nextjs.org/) è un ottimo punto di partenza. Next.js è un popolare framework leggero per la generazione di contenuto statico generato server-side con React. Include funzioni quali routing, styling e server-side rendering, che ti permetteranno di lanciare il tuo progetto rapidamente.
```

2022-07-21 16:29 UTC, mattia-sanfilippo commented on beta/src/pages/learn/start-a-new-react-project.md
> +Se preferisci impostare la tua toolchain Javascript partendo da zero, [da uno sguardo a questa guida](https://blog.usejournal.com/creating-a-react-app-from-scratch-f3c693b84658) che mostra come ricre
```suggestion
Se preferisci impostare la tua toolchain JavaScript partendo da zero, [da uno sguardo a questa guida](https://blog.usejournal.com/creating-a-react-app-from-scratch-f3c693b84658) che mostra come ricreare alcune delle funzionalità offerte da Create React App. Un framework offrirà inoltre anche soluzioni per il routing ed il data fetching. Per progetti più grandi, potresti aver bisogno di dover gestire pacchetti multipli in una repository singola usando tools come [Nx](https://nx.dev/react) o [Turborepo](https://turborepo.org/).
```

2022-07-22 11:46 UTC, mattia-sanfilippo requested changes

2022-07-22 11:46 UTC, mattia-sanfilippo commented on beta/src/pages/learn/editor-setup.md
> +In editor correttamente configurato permette una più facile lettura del codice ed una scrittura più veloce. Può anche aiutare nell'individuazione di bugs durante la battitura! Se è la prima volta che
```suggestion
Un editor correttamente configurato permette una più facile lettura del codice ed una scrittura più veloce. Può anche aiutare nell'individuazione di bugs durante la battitura! Se è la prima volta che configuri un editor o vuoi ritoccare la tua configurazione attuale, abbiamo alcune raccomandazioni.
```

2022-07-22 11:46 UTC, mattia-sanfilippo commented on beta/src/pages/learn/editor-setup.md
> +[VS Code](https://code.visualstudio.com/) è uno degli editor più popolari al momenti. Ha un grande marketplace di estensioni e si integra molto bene con servizi popolari come GitHub. Molte delle funz
```suggestion
[VS Code](https://code.visualstudio.com/) è uno degli editor più popolari al momento. Ha un grande marketplace di estensioni e si integra molto bene con servizi popolari come GitHub. Molte delle funzioni elencate di seguito possono essere aggiunte a VS Code come estensioni, rendendolo altamente configurabile!
```

2022-07-22 11:46 UTC, mattia-sanfilippo commented on beta/src/pages/learn/editor-setup.md
> +* [Vim](https://www.vim.org/) è un editor di testo altamente configurabile progettato per rendere la modifica di ogni tipo di testo molto efficiente. É incluso nella maggioranza delle distribuzoni UN
```suggestion
* [Vim](https://www.vim.org/) è un editor di testo altamente configurabile progettato per rendere la modifica di ogni tipo di testo molto efficiente. É incluso nella maggioranza delle distribuzioni UNIX e Apple OS X lanciando il comando "vi".
```

2022-07-22 11:46 UTC, mattia-sanfilippo commented on beta/src/pages/learn/editor-setup.md
> +I Code linters individuano problemi nel codice man mano che lo si scrive, permettendo di fixarli sul nascere. [ESLint](https://eslint.org/) è un linter per JavaScript open source molto popolare.
```suggestion
I code linters individuano problemi nel codice man mano che lo si scrive, permettendo di fixarli sul nascere. [ESLint](https://eslint.org/) è un linter per JavaScript open source molto popolare.
```

2022-08-01 07:48 UTC, LucaBlackDragon approved these changes

2022-08-02 12:45 UTC, merged